version: "3"

services:
   db:
      image: postgres
      environment:
         POSTGRESS_PASSWORD: yourpassword

   web:
      build: .
      volumes:
         - .:/usr/src/app
      ports:
         - "8000:8000"
